apiVersion: v1
kind: Pod
metadata:
  name: omnikube-load-generator
  labels:
    app: load-generator
spec:
  containers:
    - name: load-generator
      image: alpine:latest
      command: ["/bin/sh", "-c"]
      args:
        - while true; do echo 'stresstest' | md5sum; done
