apiVersion: v1
kind: PersistentVolume
metadata:
  name: omnikube-data-pv
  labels:
    app: omnikube-server
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  storageClassName: omnikube-storage
  hostPath:
    path: /mnt/omnikube-data
    type: DirectoryOrCreate
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: omnikube-db-pvc
  labels:
    app: omnikube-server
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: omnikube-storage
  resources:
    requests:
      storage: 1Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: omnikube-server
  labels:
    app: omnikube-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: omnikube-server
  template:
    metadata:
      labels:
        app: omnikube-server
    spec:
      containers:
        - name: omnikube-server
          image: cloudmetrics-server:latest
          imagePullPolicy: IfNotPresent
          env:
            - name: OMNIKUBE_SLACK_WEBHOOK_URL
              value: ""
            - name: OMNIKUBE_DISCORD_WEBHOOK_URL
              value: ""
            - name: OMNIKUBE_ALERT_MOCK_WEBHOOK_URL
              value: "http://127.0.0.1:5000/api/alerts/mock-webhook"
          ports:
            - name: http
              containerPort: 5000
              protocol: TCP
          volumeMounts:
            - name: database-storage
              mountPath: /data
      volumes:
        - name: database-storage
          persistentVolumeClaim:
            claimName: omnikube-db-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: omnikube-server-service
  labels:
    app: omnikube-server
spec:
  type: ClusterIP
  selector:
    app: omnikube-server
  ports:
    - name: http
      port: 80
      targetPort: 5000
      protocol: TCP
