{{- if and .Values.server.enabled .Values.server.persistence.enabled }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: omnikube-db-pvc
  labels:
    {{- include "omnikube.server.labels" . | nindent 4 }}
spec:
  accessModes:
    - ReadWriteOnce
  {{- if .Values.server.persistence.storageClass }}
  storageClassName: {{ .Values.server.persistence.storageClass | quote }}
  {{- end }}
  resources:
    requests:
      storage: {{ .Values.server.persistence.size | default "1Gi" }}
{{- end }}
