{{- if .Values.server.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "omnikube.fullname" . }}-server
  labels:
    {{- include "omnikube.server.labels" . | nindent 4 }}
spec:
  type: {{ .Values.server.service.type }}
  selector:
    {{- include "omnikube.server.selectorLabels" . | nindent 4 }}
  ports:
    - name: http
      port: {{ .Values.server.service.port }}
      targetPort: {{ .Values.server.service.targetPort }}
      protocol: TCP
{{- end }}
